// ── Auto-generated by orchestrator assembly — do NOT edit manually ──

export type AssetMeta = {
  isSprite?: boolean;
  cols?: number;
  rows?: number;
  frameCount?: number;
};

export const ASSETS: Record<string, string> = {
  "bgm_home_loop": new URL("./assets/bgm/bgm_bgm-home-loop_b351e3.mp3", import.meta.url).href,
  "sfx_box_thud": new URL("./assets/sfx/sfx_sfx-box-thud_805097.mp3", import.meta.url).href,
  "sfx_delivery_van": new URL("./assets/sfx/sfx_sfx-delivery-van_0389e3.mp3", import.meta.url).href,
  "sfx_doorbell": new URL("./assets/sfx/sfx_sfx-doorbell_6216db.mp3", import.meta.url).href,
  "sfx_garden_ambience": new URL("./assets/sfx/sfx_sfx-garden-ambience_e2a527.mp3", import.meta.url).href,
  "sfx_room_tone": new URL("./assets/sfx/sfx_sfx-room-tone_fcad8d.mp3", import.meta.url).href,
  "skin_book_cover": new URL("./assets/sprite/sprite_skin-book-cover_42d34a.webp", import.meta.url).href,
  "skin_cardboard_label": new URL("./assets/sprite/sprite_skin-cardboard-label_0f9e5b.webp", import.meta.url).href,
  "skin_ceiling": new URL("./assets/sprite/sprite_skin-ceiling_35765e.webp", import.meta.url).href,
  "skin_fabric_cream": new URL("./assets/sprite/sprite_skin-fabric-cream_66924a.webp", import.meta.url).href,
  "skin_fabric_rose": new URL("./assets/sprite/sprite_skin-fabric-rose_447efc.webp", import.meta.url).href,
  "skin_floor_plank": new URL("./assets/sprite/sprite_skin-floor-plank_344a2e.webp", import.meta.url).href,
  "skin_grass": new URL("./assets/sprite/sprite_skin-grass_bf65ad.webp", import.meta.url).href,
  "skin_picture_art": new URL("./assets/sprite/sprite_skin-picture-art_7a7f27.webp", import.meta.url).href,
  "skin_rug": new URL("./assets/sprite/sprite_skin-rug_4acf45.webp", import.meta.url).href,
  "skin_trim": new URL("./assets/sprite/sprite_skin-trim_599f44.webp", import.meta.url).href,
  "skin_vanity_door": new URL("./assets/sprite/sprite_skin-vanity-door_2b5e5d.webp", import.meta.url).href,
  "skin_wall_deep": new URL("./assets/sprite/sprite_skin-wall-deep_f071e5.webp", import.meta.url).href,
  "skin_wall_wash": new URL("./assets/sprite/sprite_skin-wall-wash_bc3055.webp", import.meta.url).href,
  "skin_wood_deep": new URL("./assets/sprite/sprite_skin-wood-deep_3d0463.webp", import.meta.url).href,
  "skin_wood_plank": new URL("./assets/sprite/sprite_skin-wood-plank_907e7b.webp", import.meta.url).href,
  "tex_cardboard_flat": new URL("./assets/sprite/sprite_tex-cardboard-flat_55c6f5.webp", import.meta.url).href,
  "tex_ceramic_flat": new URL("./assets/sprite/sprite_tex-ceramic-flat_f45292.webp", import.meta.url).href,
  "tex_fabric_cream_flat": new URL("./assets/sprite/sprite_tex-fabric-cream-flat_884ff6.webp", import.meta.url).href,
  "tex_fabric_rose_flat": new URL("./assets/sprite/sprite_tex-fabric-rose-flat_694d6d.webp", import.meta.url).href,
  "tex_wood_deep_flat": new URL("./assets/sprite/sprite_tex-wood-deep-flat_58d4ad.webp", import.meta.url).href,
  "tex_wood_warm_flat": new URL("./assets/sprite/sprite_tex-wood-warm-flat_72c8d7.webp", import.meta.url).href,
};

export const ASSET_META: Record<string, AssetMeta> = {};
